services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "54556:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

volumes:
  data:
