# Generated by Django 5.1.2 on 2024-10-25 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name="Workspace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("industry", models.CharField(max_length=100, null=True)),
                ("description", models.TextField(null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_workspaces",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "workspace",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="workspaces",
            field=models.ManyToManyField(related_name="members", to="main.workspace"),
        ),
        migrations.AddIndex(
            model_name="workspace",
            index=models.Index(fields=["name"], name="workspace_name_896c3a_idx"),
        ),
    ]
