# Generated by Django 5.1.2 on 2024-10-25 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_user_role_workspace_user_workspaces_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("schedule_time", models.DateTimeField()),
                (
                    "post_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("video", "Video"),
                            ("text", "Text"),
                        ],
                        max_length=100,
                    ),
                ),
                ("post_image", models.ImageField(null=True, upload_to="")),
                ("post_text", models.TextField(null=True)),
                ("post_video", models.FileField(null=True, upload_to="")),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(null=True)),
                ("description", models.TextField(null=True)),
                ("user_notes", models.TextField(null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "assignee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="main.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "event",
                "ordering": ["schedule_time"],
            },
        ),
        migrations.CreateModel(
            name="Reminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reminder_time", models.DateTimeField()),
                ("is_notified", models.BooleanField(default=False)),
                ("snooze_time", models.DateTimeField(null=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="main.post",
                    ),
                ),
            ],
            options={
                "db_table": "reminder",
                "ordering": ["reminder_time"],
            },
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["schedule_time"], name="event_schedul_e6a8ea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["is_completed"], name="event_is_comp_04bfdf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["is_deleted"], name="event_is_dele_5ebfe1_idx"),
        ),
        migrations.AddIndex(
            model_name="reminder",
            index=models.Index(
                fields=["reminder_time"], name="reminder_reminde_d65b1b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reminder",
            index=models.Index(
                fields=["is_notified"], name="reminder_is_noti_c1d6d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reminder",
            index=models.Index(
                fields=["snooze_time"], name="reminder_snooze__05e229_idx"
            ),
        ),
    ]
