# Generated by Django 5.1.2 on 2024-10-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_post_reminder_post_event_schedul_e6a8ea_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=128, verbose_name="Username"),
        ),
    ]
