# Generated by Django 5.1.2 on 2024-10-25 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_post_post_image_alter_post_post_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="reminder",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_reminders",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
