# Generated by Django 5.1.2 on 2024-10-25 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_reminder_creator"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostGenerationSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_generation_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_generation_sessions",
                        to="main.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "post_generation_session",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="PostGenerationSessionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("prompt", models.TextField()),
                ("response", models.TextField()),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="main.postgenerationsession",
                    ),
                ),
            ],
            options={
                "db_table": "post_generation_session_history",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="postgenerationsession",
            index=models.Index(
                fields=["created_at"], name="post_genera_created_ebe651_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="postgenerationsessionhistory",
            index=models.Index(
                fields=["created_at"], name="post_genera_created_a5d7af_idx"
            ),
        ),
    ]
