# Generated by Django 5.1.2 on 2024-10-25 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_postgenerationsession_postgenerationsessionhistory_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="session",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="main.postgenerationsession",
            ),
        ),
    ]
