# Generated by Django 5.1.2 on 2024-10-25 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_post_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="img_prompt",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="vid_prompt",
            field=models.TextField(null=True),
        ),
    ]
