# Generated by Django 5.1.2 on 2024-10-26 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_post_img_prompt_post_vid_prompt"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="fcm_token",
            field=models.TextField(null=True),
        ),
    ]
